---
name: build and push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install Docker
        run: curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3
        with:
          endpoint: "tcp://host-gateway:2375"

      - name: Login to Docker Hub
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout Repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Dotenv Action
        id: dotenv
        uses: falti/dotenv-action@v1.1.2

      - name: Build and push
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 # v6
        env:
          ACTIONS_RUNTIME_TOKEN: ''
        with:
          context: .
          file: ./Dockerfile
          build-args: VERSION=${{ steps.dotenv.outputs.version }}
          push: true
          tags: |
            ${{ steps.dotenv.outputs.repo }}:latest
            ${{ steps.dotenv.outputs.repo }}:${{ steps.dotenv.outputs.version }}
